### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by kwesiObuobi** [tsheporamantso/Portfolio#4]
## Good job so far. However, there are a few changes required. 

- Kindly add styling to the button to ensure that your project matches the Figma design.
- Please ensure there are no linter errors in your code. Use the `stylelint` command to remove any indentation
- To avoid clutter on your code, kindly remove all dead and unused comments

[Optional]
- Consider using the `::after` and `::before` pseudoelements on your universal selector.

**Comment by tsheporamantso** [comment]
Issues Resolved, thank you for the insightful recommendations.
